name: "Update Nix Flake inputs"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * 1' # runs weekly on Monday at 14:00

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v29
      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1073741824
          purge: true
          purge-prefixes: cache-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          git-author-name: 'Github Actions'
          git-author-email: 'github-actions[bot]@users.noreply.github.com'
          git-committer-name: 'Github Actions'
          git-committer-email: 'github-actions[bot]@users.noreply.github.com'
          pr-title: "Update flake.lock"
          pr-labels: |
            deps
            automated
